# -*- coding: utf-8 -*-
"""01_Pythonデータサイエンスへの第一歩:データ前処理.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17igquTCvn4j9z9F_C6gGQHx1FIUZp0j3

# Pythonデータサイエンスへの第一歩:データ前処理

**内容**

*   CSVのデータ読み込み
*   Pandas Dataframe 基本
*   データの前処理
*   データ可視化(PandasとMatplotlib)の基本


**モジュール**

* pandas
* numpy
* matplotlib
"""

import pandas as pd # 標準略語
import numpy as np #標準略語
from matplotlib import pyplot as plt #プロットのモジュール

"""## 今回のデータ

今日の授業では、ハワイのマウナロア天文台のスクリップスCO2プログラムからのCO2データを使用します。このデータセットは1958年から現在までのものです。
[サイトリンク](https://scrippsco2.ucsd.edu/data/atmospheric_co2/primary_mlo_co2_record.html)
[マウナロア天文台](https://www.google.com/maps?sca_esv=427ecd856dc6fca7&output=search&q=Mauna+Loa+Observatory+in++Hawaii&source=lnms&fbs=ABzOT_DeDz-iRlqWErVV5iq_6BbvvcMjMFuxZRtR2fSO7EG4rEOcf0AQbi9QLGlFzxBy4TVqulq5ZbhK6yapq80XVJnao02aIMkHJluF8yGVgzOm0MvGS5JpH01pjFKKtWSryDiX6FNl9FZ1kyo2UoStY9PIzLNn4q9E3sJ_OuhinxE72nsj0-8OgLI4JwHjhRKvYyAX9b7LVBM_aG8UaPo1HFtr69XkyAy6hfX3MDV8knizs7BlSIY&entry=mc&ved=1t:200715&ictx=111)

このデータをダウンロードするために、シンプルなLinuxのコマンド
[リンク ](https://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/monthly/monthly_in_situ_co2_mlo.csv)

```
wget https://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/monthly/monthly_in_situ_co2_mlo.csv
```
"""

!wget https://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/monthly/monthly_in_situ_co2_mlo.csv

"""## CSVの扱い

CSVのファイルは`.txt`のファイルと同じように開ける。
中身を確認するために便利
```
with open("{}.csv") as file:
  for i in range(100):
    line = file.readline()
    print(i,line)
```

"""

with open("monthly_in_situ_co2_mlo.csv") as file:
  for i in range(100):
    line = file.readline()
    print(i,line)

"""データの問題点

1.   データの上で情報文章があり
2.   ヘッダー列が1行以上を占める

`pandas`でうまく使うためにこの点を解決しなければなりません。

## Pandas Read_csv

```
pandas.read_csv(filepath_or_buffer, *, sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None)
```
"""

# 1 skiprows 必要ない行をスキップ
df = pd.read_csv("monthly_in_situ_co2_mlo.csv",skiprows=61)
df.head()

#2 ヘッダーを直す
header = df.keys().tolist()
print(header)
cleaned_header = [ col.strip() for col in header]
print(cleaned_header)
cleaned_header[2]="Date Excel"
print(cleaned_header[:6])

cleaned_header[:6]

df = pd.read_csv("monthly_in_situ_co2_mlo.csv",skiprows=64,names=cleaned_header[:6],usecols=cleaned_header[:6])
df.head()

"""## Pandas 基本

Dataframe ~ df


*   モジュール
*   インデクシング


"""

df.head() #最初の行を表示

df.tail() #最後の行を表示

df.info() #データ形式の情報

df.describe() #データの統計学的なまとめ

df["CO2"] #ヘッダーの名前

df.shape #行数, 列数

df.size #行数 * 列数

df.columns #列名

df.dtypes #データ形式

df.iloc[0:30] #ilocによるインデックスベースの選択

df.loc[0:30,["Date","CO2"]] #Locによるインデクシングとヘッダーの選択

#ボール値のインデクシング
df[df["CO2"]>400]

df[df["Yr"]>=2000]

df[df["CO2"]==-99.99] #NANのデータ値の取得

# 新しい列の追加
df["Year-Mn"] = df["Yr"].astype(str) + "-" + df["Mn"].astype(str)

"""## Pandas 欠損値の処理"""

df.isnull().sum() #isnull()  欠損値の数を取得

df.replace(-99.99,np.nan,inplace=True) # np.nan 欠損値を作成, ここ-99.99の値は欠損値へ変換する

df.isnull().sum()

df.dropna(inplace=True) # 欠損値を削除
#df.dropna(subset=['CO2']) #特定の列だけ
df.isnull().sum()

"""# データ可視化

* Pandasの内の手法
* matplotlibの手法

"""

df.plot(x="Date",y="CO2",title="CO2 Concentration Over Time",grid=True,figsize=(12,6),kind="line")

"""### 日本語の文字の対応

* ベストの手法: japanize-matplotlib
"""

!pip install japanize-matplotlib

import japanize_matplotlib

df.plot(x="Date",y="CO2",title="CO2 密度の時系列",grid=True,figsize=(12,6),kind="line")

"""## Matplotlibの手法"""

x = df["Date"]
y = df["CO2"]
plt.figure(figsize=(12,6)) #FIGでサイズを設定する
plt.plot(x,y)#プロット
#プロットの他の情報を追加
plt.title("CO2密度の時系列")
plt.xlabel("日付")
plt.ylabel("濃度(PPM)")
plt.grid(True)
plt.show()

df.head()

df["Mn"]

use_df = df.copy()
use_df

# Pandas のResample 目的　月の平均の移動
#手法１ DatetimeIndex
#df.index = pd.to_datetime(df["Year-Mn"])
use_df = df.copy()
use_df.index = pd.to_datetime(df["Year-Mn"])
use_df = use_df[df.index>"2000-01-01"]
df_Mn_mean=use_df.groupby("Mn")["CO2"].mean()
df_Mn_std=use_df.groupby("Mn")["CO2"].std()

x=np.arange(1,13)
y=df_Mn_mean
y_err=df_Mn_std
plt.figure(figsize=(12,6)) #FIGでサイズを設定する
plt.plot(x,y,label="mean", marker='o')#プロット
plt.fill_between(x, y + y_err, y - y_err, alpha=0.2, color='teal')
#plt.errorbar(x, y, yerr = y_err, capsize=5, fmt='o', markersize=10, ecolor='black', markeredgecolor = "black", color='w')

#プロットの他の情報を追加
plt.title("CO2密度の時系列 2000年から")
plt.xlabel("月")
plt.ylabel("濃度(PPM)")
plt.grid(True)
plt.show()

df_clean

"""### Box plot"""

# Rolling 12-month mean
use_df = df.copy()
use_df.index = pd.to_datetime(df["Year-Mn"])
use_df["RollingMean"] = use_df["CO2"].rolling(window=12, center=True).mean()

# Residual = Actual CO2 - Rolling Mean
use_df["Residual"] = use_df["CO2"] - use_df["RollingMean"]

# Drop NaNs caused by rolling
df_clean = use_df.dropna(subset=["Residual"])

# Plot boxplot of residuals grouped by month
plt.figure(figsize=(12, 6))
df_clean.boxplot(column="Residual", by="Mn", grid=True)
plt.title("月別のCO2濃度の変動（年平均からの差）")
plt.suptitle("")  # Remove automatic suptitle
plt.xlabel("月")
plt.ylabel("年平均からの差 (PPM)")
plt.show()

"""### Linear regression 線形回帰"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Group data by year and get yearly average CO2
use_df=df.copy()
yearly = df.groupby("Yr")["CO2"].mean().reset_index()

# Extract X and Y for regression
X = yearly["Yr"].values
Y = yearly["CO2"].values

# Linear regression using numpy
# Fit line: Y = a * X + b
a, b = np.polyfit(X, Y, 1)  # 1 = linear

# Print the slope
print(f"年間平均の増加率: {a:.2f} ppm/年")

# Optional: Plot it
plt.figure(figsize=(12,6))
plt.plot(X, Y, label="年平均CO2", marker='o')
plt.plot(X, a * X + b, color='red', label=f"回帰直線: {a:.2f} ppm/年")
plt.xlabel("年")
plt.ylabel("CO2濃度 (PPM)")
plt.title("年平均CO2濃度と線形回帰")
plt.legend()
plt.grid(True)
plt.show()

